### ISSUE TITLE
Adopt semver version

### ISSUE THREAD

**Issue by joaomoreno** [ronnidc/vscode-nunjucks#1]
Hi, VS Code developer here. Due to a recent change, the next version of Code will require every extension to have a [semver](http://semver.org/) compatible version. `nunjucks` is one of the very few that doesn't have one; its latest version seems to be [0.0.2.1](https://marketplace.visualstudio.com/items/ronnidc.nunjucks).

In order to stay compatible with Code, could you publish a more recent version using a semver compatible version number?

Related to Microsoft/vscode-vsce#55 and Microsoft/vscode#1111

**Comment by Eldblom** [comment]
This is a breaking bug, as code now no longer loads the extension. Please fix version to 0.2.1.

**Comment by ronnidc** [comment]
Version is now changed to a semver compatible version
