### ISSUE TITLE
Support for njk extension

### ISSUE THREAD

**Issue by mrmlnc** [ronnidc/vscode-nunjucks#5]
Source: http://mozilla.github.io/nunjucks/templating.html

> Although you are free to use any file extension you wish for your Nunjucks template files, the Nunjucks community has adopted .njk.

> If you are developing tools or editor syntax helpers for Nunjucks, please include recognition of the .njk extension.

**Comment by mrmlnc** [comment]
@ronnidc ping :dancers:

**Comment by ronnidc** [comment]
Hi mrmlnc,

Sorry for my late respons, I have been on 4 weeks vacation without opening my laptop.

I will asap update the extension on Visual Studio Marketplace.

Back when I first created the extension there was no recommendation to find in the documentation other than .html. At my workplace  we therefor went along with the short version .nj. We might ofcourse change that to .njk now that it's a standard. 

Thank you for your contribution to the extension.

**Comment by ronnidc** [comment]
The extension is updated to support recognition og the .njk extension.
https://marketplace.visualstudio.com/items?itemName=ronnidc.nunjucks

**Comment by mrmlnc** [comment]
@ronnidc, thanks :+1:
